name: Different Jobs for Different steps
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  test-code:
    needs: lint
    runs-on: ubuntu-latest 
    steps:
      - name: Get Code into Runner Machine
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
  deploy:
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Deploy Application
        run: echo "deploying..."